// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCaxUHLiFEgWqdTaZcks0I9bwfE4cwoXU',
    appId: '1:798788567053:web:60c5931f76691449549544',
    messagingSenderId: '798788567053',
    projectId: 'homeworx-19876',
    authDomain: 'homeworx-19876.firebaseapp.com',
    storageBucket: 'homeworx-19876.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3fdrCNBDzAbDmwMrXXdGp1EKZQ9a-93w',
    appId: '1:798788567053:android:060d8e227b250121549544',
    messagingSenderId: '798788567053',
    projectId: 'homeworx-19876',
    storageBucket: 'homeworx-19876.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9DDCzbxl58fhR8bgNOBVaIdrnJVL-yZ0',
    appId: '1:798788567053:ios:e1491252f5ed4d23549544',
    messagingSenderId: '798788567053',
    projectId: 'homeworx-19876',
    storageBucket: 'homeworx-19876.firebasestorage.app',
    iosBundleId: 'com.yourdomain.homeServiceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9DDCzbxl58fhR8bgNOBVaIdrnJVL-yZ0',
    appId: '1:798788567053:ios:e1491252f5ed4d23549544',
    messagingSenderId: '798788567053',
    projectId: 'homeworx-19876',
    storageBucket: 'homeworx-19876.firebasestorage.app',
    iosBundleId: 'com.yourdomain.homeServiceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCaxUHLiFEgWqdTaZcks0I9bwfE4cwoXU',
    appId: '1:798788567053:web:d214f0c84ad86dc6549544',
    messagingSenderId: '798788567053',
    projectId: 'homeworx-19876',
    authDomain: 'homeworx-19876.firebaseapp.com',
    storageBucket: 'homeworx-19876.firebasestorage.app',
  );
}
